import Heading from "../components/Heading";
import Image from "next/image";
import {GetStaticProps} from 'next';
import {bonusCardType} from "../types";
import { Swiper, SwiperSlide } from "swiper/react";
import { Swiper as SwiperType, Navigation, Autoplay, Controller, Pagination} from "swiper";
import styles from '../styles/Home.module.scss'
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/bundle";
import "swiper/css/navigation";
import Bonuses from "../components/Bonuses";
import React, {FC, useRef} from "react";

type bonusCardProps = {
    bonuses: [bonusCardType]
}

// export const swiperRef = useRef<SwiperType>()

export const getStaticProps:GetStaticProps = async () => {
    const response = await fetch(`${process.env.API_HOST}/bonuses/`);
    const data = await response.json();

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: {bonuses: data}
    }
}

const Home:FC<bonusCardProps> = ({bonuses}) => {
    const swiperRef = useRef<SwiperType>();
        return (
    <>
        <div className='description'>
            <Heading text={'Best Bonuses Lorem Ipsum'} tag={'h2'}/>
            <Heading text={'Welcome, all you passionate Australian online casino players out there! If you a rookie looking for some quick guidelines on how to get started or a seasoned player searching for some fresh real money casino recommendations, you\'ve reached the right spot at True Blue!'} tag={'h3'}/>
            </div>
        <div className='tabs-group'>
            <button className='btn-blue__active'>No deposit bonus</button>
            <button className='btn-blue'>Welcome bonus</button>
            <button className='btn-blue'>Free Spins bonus</button>
        </div>
        <Swiper
            slidesPerView={5}
            //cssMode={true}
            slidesPerGroup={5}
            spaceBetween={5}
            pagination={{
                clickable: true,
                bulletElement: 'div'
            }}
            createElements={true}
            navigation={{nextEl:'.new-swiper-button-next', prevEl: '.new-swiper-button-prev',}}
            keyboard={true}
            onBeforeInit={(swiper) => {
                swiperRef.current = swiper;
            }}
            breakpoints={{
                "@0.00": {
                    slidesPerView: 1,
                    spaceBetween: 5,
                },
                "@0.75": {
                    slidesPerView: 3,
                    spaceBetween: 5,
                },
                "@1.00": {
                    slidesPerView: 5,
                    spaceBetween: 5,
                },
                "@1.50": {
                    slidesPerView: 5,
                    spaceBetween: 5,
                },
            }}
            modules={[Pagination, Navigation, Autoplay]}
            className="mySwiper"
        >
            {
                bonuses && bonuses.map((bonus) => (
            <SwiperSlide>
                <Bonuses bonus={bonus}/>
            </SwiperSlide>))}
        </Swiper>
        <div>
            <button onClick={() => swiperRef.current?.slidePrev()} className={'swiper-button-prev'}></button>
            <button onClick={() => swiperRef.current?.slideNext()} className={'swiper-button-next'}></button>
        </div>
    </>)
};

export default Home;

//
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.scss'
//
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//
//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>
//
//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>
//
//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>
//
//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//
//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
